version: "3.9"

services:
  stashly:
    image: hibare/stashly
    container_name: stashly
    hostname: stashly
    volumes:
      - ./data/stashly:/etc/stashly
    networks:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

networks:
  db:
    name: db
    external: true
    driver: overlay
