postgres:
    host: ""
    port: ""
    user: ""
    password: ""
s3:
    endpoint: ""
    region: ""
    access-key: ""
    secret-key: ""
    bucket: ""
    prefix: ""
backup:
    retention-count: "" 
    cron: ""
    encrypt: ""
encryption:
    gpg:
        key-server: ""
        key-id: ""
notifiers:
    enabled: ""
    discord:
        enabled: ""
        webhook: ""