name: Test, Build & Publish

on:
  push:
    tags:
      - "v*"
    branches:
      - main

  pull_request:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      - "**/README.md"
      - "**/Makefile"
      - "**/.env.**"
      - "**/docker-compose.*.yml"
      - "**/.vscode"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      GOLANGCI_LINT_VERSION: v2.4.0
      GOLANGCI_LINT_BIN_DIR: $HOME/.cache/golangci-lint

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"

      - name: Cache golangci-lint
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ${{ env.GOLANGCI_LINT_BIN_DIR }}
          key: golangci-lint-${{ env.GOLANGCI_LINT_VERSION }}

      - name: Ensure golangci-lint is installed
        run: |
          set -e
          GOLANGCI_LINT_BIN="$GOLANGCI_LINT_BIN_DIR/golangci-lint"
          if [ -x "$GOLANGCI_LINT_BIN" ]; then
            echo "golangci-lint found in cache."
          else
            echo "Installing golangci-lint $GOLANGCI_LINT_VERSION..."
            mkdir -p "$GOLANGCI_LINT_BIN_DIR"
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$GOLANGCI_LINT_BIN_DIR" "$GOLANGCI_LINT_VERSION"
          fi

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  docker-image-test-publish:
    # Trigger on pull request, push to main and tag creation
    runs-on: ubuntu-latest
    needs: [run-tests]
    permissions:
      contents: write
      id-token: write # For cosign
      packages: write # For GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.1.1

      - name: Set Metadata
        id: set-metadata
        run: |
          DOCKER_TAGS="unknown"
          VERSION="unknown"
          IMAGE_NAMES="hibare/stashly ghcr.io/hibare/stashly"

          if [ "${{ github.event_name }}" == "push" ]; then
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              DOCKER_TAGS="next"
              VERSION="next"
            elif [[ "${{ github.ref }}" == "refs/tags/v"* ]]; then
              DOCKER_TAGS="type=semver,pattern={{version}} type=semver,pattern={{major}}"
              VERSION="${GITHUB_REF#refs/tags/v}"
            else
              echo "Unknown ref: ${{ github.ref }}"
              exit 1
            fi
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            DOCKER_TAGS="test"
            VERSION="test"
          else
            echo "Unknown event: ${{ github.event_name }}"
            exit 1
          fi

          GOLANG_VERSION=$(grep -oP '^go (\d+(\.\d+)*)' go.mod | awk '{print $2}')

          echo "docker_image_names=$IMAGE_NAMES" >> $GITHUB_OUTPUT
          echo "docker_tags=$DOCKER_TAGS" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "golang_version=$GOLANG_VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: image-build-publish
        uses: hibare/.github/github/shared-workflows/docker-image-build-publish@f19c582cd7572c97ceb4a0a993b697ab206768f7 # v0.7.0
        with:
          image_names: ${{ steps.set-metadata.outputs.docker_image_names }}
          tags: ${{ steps.set-metadata.outputs.docker_tags }}
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
          push_dockerhub: ${{ github.event_name != 'pull_request' }}
          push_ghcr: ${{ github.event_name != 'pull_request' }}
          build_args: VERSION=${{ steps.set-metadata.outputs.version }} GOLANG_VERSION=${{ steps.set-metadata.outputs.golang_version }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
